/*
 * bayan_ffi.h: the C interface between a BayanDocs shell and the engine (engine protocol v0, docs/specs/engine-protocol.md §3).
 *
 * PROVISIONAL. The real header is generated by cbindgen in bayan-core (work package CORE-007) and shipped in its C SDK. Until that SDK
 * exists, bayan-desktop builds against this hand-written copy and a stub engine that implements it (src/engine/stub). The specification
 * names the functions but not their exact C signatures; where this file had to choose (a length for every buffer, status codes, how blobs
 * are read back), the choices are listed in the DESK-001 pull request so that CORE-007 can adopt or change them. Build with
 * BAYAN_ENGINE=sdk to use the SDK's header and library instead.
 *
 * Rules for callers:
 * - All JSON is UTF-8 and is passed with an explicit length; it is not NUL-terminated.
 * - Pointers passed to the engine are borrowed only for the duration of the call.
 * - The engine runs on its own thread and calls the message callback on that thread, one message at a time.
 * - The json pointer given to the callback is valid only during the call: copy the bytes and hand them to your own thread.
 * - Never call back into the engine from inside the callback (spec §8).
 * - bayan_engine_free blocks until the engine thread has stopped; after it returns, the callback is never called again.
 * - No function lets a C++ exception or a Rust panic escape; failures are reported through return values and engine.error messages.
 */

#ifndef BAYAN_FFI_H
#define BAYAN_FFI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* An engine instance. Opaque: only pointers to it exist outside the engine. */
typedef struct BayanEngine BayanEngine;

/* Identifies a blob (bulk bytes kept by the engine, such as file contents). 0 is never a valid blob. */
typedef uint64_t BayanBlobId;

/* Result of a call. */
typedef int32_t BayanStatus;
#define BAYAN_STATUS_OK 0
#define BAYAN_STATUS_INVALID_ARGUMENT 1 /* a null pointer, a malformed request, or a size outside the engine's limits */
#define BAYAN_STATUS_NOT_FOUND 2        /* unknown blob, document or page */
#define BAYAN_STATUS_BUFFER_TOO_SMALL 3 /* the output buffer is too small; see the function for how to learn the size needed */
#define BAYAN_STATUS_INTERNAL_ERROR 4   /* the engine failed; it also reports an engine.error message */

/* Receives messages from the engine (replies and events), on the engine thread. */
typedef void (*BayanMessageCallback)(void *user_data, const uint8_t *json, size_t json_len);

/* The engine's semantic version, as a static NUL-terminated string. */
const char *bayan_version(void);

/* Creates an engine from a JSON configuration object. Returns NULL on failure. */
BayanEngine *bayan_engine_new(const uint8_t *config_json, size_t config_len);

/* Stops and destroys an engine. Blocks until the engine thread has stopped. Accepts NULL. */
void bayan_engine_free(BayanEngine *engine);

/* Registers the message callback. Call once, before the first bayan_engine_post. */
BayanStatus bayan_engine_set_callback(BayanEngine *engine, BayanMessageCallback callback, void *user_data);

/* Queues one message (a protocol envelope, spec §4) for the engine thread. Returns without waiting for it to be processed. */
BayanStatus bayan_engine_post(BayanEngine *engine, const uint8_t *json, size_t json_len);

/* Copies bytes into a new blob. Returns its identifier, or 0 on failure. */
BayanBlobId bayan_blob_put(BayanEngine *engine, const uint8_t *bytes, size_t len);

/* Copies a blob's bytes into out, which has room for out_capacity bytes, and sets *out_len to the blob's size.
 * If out is too small (or NULL), returns BAYAN_STATUS_BUFFER_TOO_SMALL and still sets *out_len, so callers can ask for the size first. */
BayanStatus bayan_blob_get(BayanEngine *engine, BayanBlobId blob, uint8_t *out, size_t out_capacity, size_t *out_len);

/* Releases a blob. */
BayanStatus bayan_blob_release(BayanEngine *engine, BayanBlobId blob);

/* Renders a tile synchronously into a caller-provided buffer of premultiplied RGBA8 pixels, rows top to bottom.
 * - request_json: a render.tile payload (spec §6): doc_id, page, rect (x, y, width and height in BLU), zoom, device_scale and mode.
 * - width, height: the tile's size in pixels. The engine refuses tiles larger than its limits with BAYAN_STATUS_INVALID_ARGUMENT.
 * - stride: the distance between the starts of two rows, in bytes; at least 4 bytes per pixel times width.
 * - out_capacity: the size of rgba_out in bytes; at least stride times (height - 1), plus 4 times width. */
BayanStatus bayan_render_tile(BayanEngine *engine, const uint8_t *request_json, size_t request_len, uint8_t *rgba_out, size_t out_capacity,
                              uint32_t width, uint32_t height, size_t stride);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* BAYAN_FFI_H */
